### ISSUE TITLE
Tools folder are always created at the workspace root

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/bakery#100]
if I keep my cake scripts in a folder called `scripts` and open vscode with bakery globally installed and the workspace root one level up, it will restore packages to the workspace root.

I tried adding a `cake.config` to the workspace root, but that doesn't seem to be respected.

**What happens**

```
- scripts
  - build.cake
- tools
- foo.txt
```

**What is expected**

```
- scripts
  - tools
  - build.cake
- foo.txt
```

**Comment by serialprimate** [comment]
This issue might be related to:

System.IO.FileNotFoundException: Cake is not installed. Path c:/git/redacted/tools/Cake/Cake.Core.dll does not exist.
   at OmniSharp.Cake.CakeProjectSystem.GetProject(CakeScript cakeScript, String filePath)
   at OmniSharp.Cake.CakeProjectSystem.AddCakeFile(String cakeFilePath)

I have been using a 'build' directory.

Matt

**Comment by vchirikov** [comment]
Any workaround?
